In [1]:
import yfinance as yf
import pandas as pd

In [2]:
activestocks = pd.read_csv('./data/active stocks.csv')

In [3]:
activestocks.shape

(614, 1)

In [4]:
activestocks

        A
0      AA
1     AAL
2     AAP
3    AAPL
4    ABBV
..    ...
609   YUM
610   ZBH
611  ZBRA
612  ZION
613   ZTS

[614 rows x 1 columns]

In [5]:
#listofstocks = activestocks.values.tolist()

In [6]:
names = activestocks['A'].tolist()

In [7]:
names

['AA',
 'AAL',
 'AAP',
 'AAPL',
 'ABBV',
 'ABC',
 'ABMD',
 'ABT',
 'ACN',
 'ADBE',
 'ADCT',
 'ADI',
 'ADM',
 'ADP',
 'ADS',
 'ADSK',
 'ADT',
 'AEE',
 'AEP',
 'AES',
 'AFL',
 'AIG',
 'AIV',
 'AIZ',
 'AJG',
 'AKAM',
 'ALB',
 'ALGN',
 'ALK',
 'ALL',
 'ALLE',
 'ALTR',
 'ALXN',
 'AMAT',
 'AMCR',
 'AMD',
 'AME',
 'AMG',
 'AMGN',
 'AMP',
 'AMT',
 'AMZN',
 'AN',
 'ANET',
 'ANF',
 'ANSS',
 'ANTM',
 'AON',
 'AOS',
 'APA',
 'APD',
 'APH',
 'APTV',
 'ARE',
 'ARNC',
 'ASH',
 'AT',
 'ATI',
 'ATO',
 'ATVI',
 'AVB',
 'AVGO',
 'AVY',
 'AWK',
 'AXP',
 'AYI',
 'AZO',
 'BA',
 'BAC',
 'BAX',
 'BBBY',
 'BBY',
 'BC',
 'BDX',
 'BEAM',
 'BEN',
 'BF_B',
 'BHF',
 'BIG',
 'BIIB',
 'BIO',
 'BK',
 'BKNG',
 'BKR',
 'BLK',
 'BLL',
 'BMY',
 'BR',
 'BRK_B',
 'BSX',
 'BTU',
 'BUD',
 'BWA',
 'BXP',
 'C',
 'CAG',
 'CAH',
 'CARR',
 'CAT',
 'CB',
 'CBOE',
 'CBRE',
 'CC',
 'CCI',
 'CCL',
 'CCU',
 'CDNS',
 'CDW',
 'CE',
 'CERN',
 'CF',
 'CFG',
 'CHD',
 'CHK',
 'CHRW',
 'CHTR',
 'CI',
 'CIEN',
 'CINF',
 'CIT',
 'CL',
 'CLF',
 'CLX',
 'CMA',
 'CMCSA',
 'CME',
 'CMG',
 'CMI',
 'CMS',
 'CNC',
 'CNP',
 'CNX',
 'COF',
 'COG',
 'COO',
 'COP',
 'COST',
 'COTY',
 'CPB',
 'CPRI',
 'CPRT',
 'CRM',
 'CSCO',
 'CSX',
 'CTAS',
 'CTLT',
 'CTSH',
 'CTVA',
 'CTXS',
 'CVS',
 'CVX',
 'D',
 'DAL',
 'DD',
 'DDS',
 'DE',
 'DELL',
 'DFS',
 'DG',
 'DGX',
 'DHI',
 'DHR',
 'DIS',
 'DISCA',
 'DISCK',
 'DISH',
 'DLR',
 'DLTR',
 'DNB',
 'DOV',
 'DOW',
 'DPZ',
 'DRE',
 'DRI',
 'DTE',
 'DUK',
 'DVA',
 'DVN',
 'DXC',
 'DXCM',
 'DYN',
 'EA',
 'EBAY',
 'ECL',
 'ED',
 'EFX',
 'EIX',
 'EL',
 'EMN',
 'EMR',
 'ENDP',
 'ENPH',
 'EOG',
 'EQ',
 'EQIX',
 'EQR',
 'EQT',
 'ES',
 'ESS',
 'ETN',
 'ETR',
 'ETSY',
 'EVRG',
 'EW',
 'EXC',
 'EXPD',
 'EXPE',
 'EXR',
 'F',
 'FANG',
 'FAST',
 'FB',
 'FBHS',
 'FCX',
 'FDX',
 'FE',
 'FFIV',
 'FHN',
 'FIS',
 'FISV',
 'FITB',
 'FL',
 'FLIR',
 'FLR',
 'FLS',
 'FLT',
 'FMC',
 'FOSL',
 'FOX',
 'FOXA',
 'FRC',
 'FRT',
 'FRX',
 'FSLR',
 'FTI',
 'FTNT',
 'FTV',
 'GCI',
 'GD',
 'GE',
 'GHC',
 'GILD',
 'GIS',
 'GL',
 'GLW',
 'GM',
 'GME',
 'GNW',
 'GOOG',
 'GOOGL',
 'GPC',
 'GPN',
 'GPS',
 'GRMN',
 'GS',
 'GT',
 'GWW',
 'H',
 'HAL',
 'HAS',
 'HBAN',
 'HBI',
 'HCA',
 'HD',
 'HES',
 'HFC',
 'HIG',
 'HII',
 'HLT',
 'HOG',
 'HOLX',
 'HON',
 'HP',
 'HPE',
 'HPQ',
 'HRB',
 'HRL',
 'HSIC',
 'HST',
 'HSY',
 'HUM',
 'HWM',
 'IBM',
 'ICE',
 'IDXX',
 'IEX',
 'IFF',
 'IGT',
 'ILMN',
 'INCY',
 'INFO',
 'INTC',
 'INTU',
 'IP',
 'IPG',
 'IPGP',
 'IQV',
 'IR',
 'IRM',
 'ISRG',
 'IT',
 'ITT',
 'ITW',
 'IVZ',
 'J',
 'JBHT',
 'JBL',
 'JCI',
 'JEF',
 'JKHY',
 'JNJ',
 'JNPR',
 'JPM',
 'JWN',
 'K',
 'KBH',
 'KEY',
 'KEYS',
 'KHC',
 'KIM',
 'KLAC',
 'KMB',
 'KMI',
 'KMX',
 'KO',
 'KR',
 'KSS',
 'KSU',
 'L',
 'LB',
 'LDOS',
 'LEG',
 'LEN',
 'LH',
 'LHX',
 'LIFE',
 'LIN',
 'LKQ',
 'LLY',
 'LMT',
 'LNC',
 'LNT',
 'LOW',
 'LRCX',
 'LSI',
 'LUMN',
 'LUV',
 'LVS',
 'LW',
 'LYB',
 'LYV',
 'M',
 'MA',
 'MAA',
 'MAC',
 'MAR',
 'MAS',
 'MAT',
 'MBI',
 'MCD',
 'MCHP',
 'MCK',
 'MCO',
 'MDLZ',
 'MDP',
 'MDT',
 'MET',
 'MGM',
 'MHK',
 'MKC',
 'MKTX',
 'MLM',
 'MMC',
 'MMI',
 'MMM',
 'MNST',
 'MO',
 'MOS',
 'MPC',
 'MRK',
 'MRO',
 'MS',
 'MSCI',
 'MSFT',
 'MSI',
 'MTB',
 'MTD',
 'MTG',
 'MTW',
 'MU',
 'MUR',
 'MXIM',
 'NAVI',
 'NBR',
 'NCLH',
 'NCR',
 'NDAQ',
 'NEE',
 'NEM',
 'NFLX',
 'NI',
 'NKE',
 'NKTR',
 'NLOK',
 'NLSN',
 'NOC',
 'NOV',
 'NOW',
 'NRG',
 'NSC',
 'NTAP',
 'NTRS',
 'NUE',
 'NVDA',
 'NVR',
 'NWL',
 'NWS',
 'NWSA',
 'NYT',
 'O',
 'ODFL',
 'ODP',
 'OI',
 'OKE',
 'OMC',
 'ORCL',
 'ORLY',
 'OTIS',
 'OXY',
 'PAYC',
 'PAYX',
 'PBCT',
 'PBI',
 'PCAR',
 'PCG',
 'PD',
 'PDCO',
 'PEAK',
 'PEG',
 'PEP',
 'PFE',
 'PFG',
 'PG',
 'PGR',
 'PH',
 'PHM',
 'PKG',
 'PKI',
 'PLD',
 'PLL',
 'PM',
 'PNC',
 'PNR',
 'PNW',
 'POOL',
 'PPG',
 'PPL',
 'PRGO',
 'PRU',
 'PSA',
 'PSX',
 'PVH',
 'PWR',
 'PXD',
 'PYPL',
 'QCOM',
 'QEP',
 'QRVO',
 'R',
 'RCL',
 'RE',
 'REG',
 'REGN',
 'RF',
 'RHI',
 'RIG',
 'RJF',
 'RL',
 'RMD',
 'ROK',
 'ROL',
 'ROP',
 'ROST',
 'RRC',
 'RRD',
 'RSG',
 'RTX',
 'SANM',
 'SBAC',
 'SBUX',
 'SCHW',
 'SE',
 'SEE',
 'SHW',
 'SIG',
 'SII',
 'SIVB',
 'SJM',
 'SLB',
 'SLG',
 'SLM',
 'SNA',
 'SNPS',
 'SNV',
 'SO',
 'SPG',
 'SPGI',
 'SRCL',
 'SRE',
 'SSP',
 'STE',
 'STT',
 'STX',
 'STZ',
 'SUN',
 'SUNW',
 'SWK',
 'SWKS',
 'SWN',
 'SYF',
 'SYK',
 'SYY',
 'T',
 'TAP',
 'TDC',
 'TDG',
 'TDY',
 'TEL',
 'TER',
 'TEX',
 'TFC',
 'TFX',
 'TGNA',
 'TGT',
 'THC',
 'TJX',
 'TMO',
 'TMUS',
 'TPR',
 'TRIP',
 'TRMB',
 'TROW',
 'TRV',
 'TSCO',
 'TSLA',
 'TSN',
 'TT',
 'TTWO',
 'TWTR',
 'TXN',
 'TXT',
 'TYL',
 'UA',
 'UAA',
 'UAL',
 'UDR',
 'UHS',
 'UIS',
 'ULTA',
 'UNH',
 'UNM',
 'UNP',
 'UPS',
 'URBN',
 'URI',
 'USB',
 'V',
 'VAR',
 'VFC',
 'VIAC',
 'VLO',
 'VMC',
 'VNO',
 'VNT',
 'VRSK',
 'VRSN',
 'VRTX',
 'VTR',
 'VTRS',
 'VZ',
 'WAB',
 'WAT',
 'WB',
 'WBA',
 'WDC',
 'WEC',
 'WELL',
 'WEN',
 'WFC',
 'WHR',
 'WLTW',
 'WM',
 'WMB',
 'WMT',
 'WRB',
 'WRK',
 'WST',
 'WU',
 'WY',
 'WYNN',
 'X',
 'XEC',
 'XEL',
 'XL',
 'XLNX',
 'XOM',
 'XRAY',
 'XRX',
 'XYL',
 'YUM',
 'ZBH',
 'ZBRA',
 'ZION',
 'ZTS']

In [8]:
#stocks_download = yf.download(activestocks, 
#                     start='2019-01-01', 
#                      end='2019-12-31', 
#                      progress=False)
#stocks_download.head()

In [9]:
#tsla_df = yf.download('TSLA', 
#                     start='2019-01-01', 
#                     end='2019-12-31', 
#                      progress=False)
#tsla_df.head()

In [10]:
stocks = ['TSLA', 'AAPL']

In [11]:
type(stocks)

list

In [22]:
stocks_df = yf.download(names, 
                      start='2004-01-01', 
                      end='2021-03-17', 
                      progress=False)
stocks_df.head()

2 Failed downloads:
- BRK_B: No data found, symbol may be delisted
- BF_B: No data found for this date range, symbol may be delisted

            Adj Close                                                 \
                   AA AAL        AAP      AAPL ABBV        ABC  ABMD
Date
2004-01-02  72.434738 NaN  25.583614  0.325548  NaN  10.688442  7.00
2004-01-05  74.807442 NaN  25.351082  0.339163  NaN  11.050653  6.91
2004-01-06  74.248016 NaN  25.803566  0.337939  NaN  11.005128  6.99
2004-01-07  73.688583 NaN  26.614231  0.345589  NaN  11.112016  7.16
2004-01-08  74.575981 NaN  25.910389  0.357368  NaN  11.058571  7.29

                                             ...      Volume              \
                  ABT        ACN       ADBE  ...        XLNX         XOM
Date                                         ...
2004-01-02  13.779174  19.398138  19.518400  ...   4629200.0  12180000.0
2004-01-05  13.779174  19.951941  19.867832  ...   8452700.0  14668100.0
2004-01-06  13.678965  19.719944  19.887802  ...   5549200.0  12364400.0
2004-01-07  13.823390  19.270910  19.694550  ...   6727300.0  13561500.0
2004-01-08  13.416640  18.627302  18.975479  ...  10195400.0  14608300.0

                                                                      \
                 XRAY        XRX XYL        YUM        ZBH      ZBRA
Date
2004-01-02   502800.0  1722800.0 NaN  3226200.0   668100.0  339900.0
2004-01-05   856400.0  1562800.0 NaN  2716000.0  1188200.0  640950.0
2004-01-06  1152000.0  4152800.0 NaN  4142100.0  1167200.0  311700.0
2004-01-07   826600.0  1605900.0 NaN  3602900.0   840900.0  495150.0
2004-01-08   765600.0  1886100.0 NaN  2597800.0  1081700.0  290850.0


                ZION ZTS
Date
2004-01-02  462900.0 NaN
2004-01-05  598400.0 NaN
2004-01-06  612200.0 NaN
2004-01-07  754700.0 NaN
2004-01-08  504000.0 NaN

[5 rows x 3684 columns]

In [23]:
type(stocks_df)

pandas.core.frame.DataFrame

In [24]:
stocks_adjclose = stock_df['Adj Close']

In [26]:
stocks_adjclose.to_csv("./archive(1)/stocks_adjclose.csv")